apiVersion: v1
kind: Pod
metadata:
  name: crash-app
spec:
  containers:
    - name: app
      image: busybox:1.36
      command: ["/bin/sh", "-c", "echo starting app; while true; do echo app running; sleep 10; done"]
