apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/brixdorf/devops-heros.git
    targetRevision: main
    path: "Session-20 (Monitoring, Observability & GitOps)/03-gitops/manifests"
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
